### ISSUE TITLE
consider including the facebook account id in the scraped posts 

### ISSUE THREAD

**Issue by IvanTrendafilov** [sokomishalov/skraper#109]
It is useful to get certain things, e.g.

```https://graph.facebook.com/{facebook_account_id}/picture?type=large``` returns the profile picture (no auth) and  ``` https://www.facebook.com/{facebook_account_id}/videos/{post_id}/ ``` returns a video

**Comment by sokomishalov** [comment]
You may take a profile picture and other user related info with `Skraper.getPageInfo(...)` or `FacebookSkraper.getUserInfo(...)`.
What about video - I suppose this data contains in posts attachments, isn't it?

**Comment by IvanTrendafilov** [comment]
That's a fair point, but both the profile picture and the post attachments are CDN links and these are set to expire within a few weeks at most and then become invalid URLs. In contrast, the graph endpoint above always returns the most recent valid CDN link and the video endpoint is a permalink.

**Comment by sokomishalov** [comment]
Fair enough, but there is an opposite side.
Direct links have an advantage in some cases. For example when we need to download some kind of media or render it in some "ImageView" or "VideoView" on platforms. So it is an arguable issue and there is no ideal solution. 
From my perspective, direct links are more useful, however, some of them are not permanent, unfortunately.
But I'm always ready to discuss it.

**Comment by IvanTrendafilov** [comment]
Oh, absolutely. I am not suggesting replacing the direct links that skraper returns, these are very valuable too and great as-is. I'm only suggesting that including the facebook account id in the returned object per post is useful as (a) an identifier of where the post is coming from and (b) to potentially build permalinks using it (if a user wants to do that).

**Comment by sokomishalov** [comment]
Ah, I finally got your point clearly.
Well, I agree it could be useful, but it could be hard to adapt to other providers' data.

**Comment by Gaarv** [comment]
For facebook, it should be available just like posts from json data with `entity_id`.
For twitter it's `background-image: url(https://pbs.twimg.com/profile_banners/<user_id>/...`
But yeah, that would be many others to fill.

As for adding it into the provider model, maybe "ownerId" along with "owner" which could be `path to user/community/channel/topic/trend` from input ? Could be useful having it in data besides filename.

What do you think ?
