### ISSUE TITLE
Facebook page doesn't return any posts

### ISSUE THREAD

**Issue by ZueFe** [sokomishalov/skraper#120]
Hello,

been wondering if you could help me out with this. When I run your FB scraper on this page: https://www.facebook.com/arrowsostrava/ it doesn't return any posts. Any thought on where the problem could be or how to fix it?
Thanks.

**Comment by sokomishalov** [comment]
Hi!
For some weird reason, Facebook returns 500 status code for this page when you are unauthorized while other pages work just fine. So it looks like a Facebook backend bug.
![image](https://user-images.githubusercontent.com/21218309/107118099-f1b95880-688f-11eb-8005-d786d3295f38.png)

**Comment by ZueFe** [comment]
thanks for the info, is there a possibility it's some weird page settings? like that you can only see it when you are logged in?

**Comment by sokomishalov** [comment]
I haven’t seen such troubles before, so maybe yes

**Comment by interzone2** [comment]
I'm curious how to scrape a personal page when Facebook requires that you login to do so? I have empty results when trying to scrape my profile?
