### ISSUE TITLE
Instagram Hashtag Search

### ISSUE THREAD

**Issue by crxlunch** [sokomishalov/skraper#124]
can we get data Instagram Hashtag Search?

**Comment by sokomishalov** [comment]
Thanks for the issue!
Well, it's not implemented for now, but it is definitely in our plans.

**Comment by sokomishalov** [comment]
Will be added in 0.7.x (https://github.com/sokomishalov/skraper/commit/f1cf8874e3286548a3e028219615fecbb6275966)
