### ISSUE TITLE
Number of posts always the same for facebook scrape

### ISSUE THREAD

**Issue by Lod3** [sokomishalov/skraper#148]
Seems like when I put in this command 
``` 
.\skraper facebook MuziekcentrumKinkyStar -n 200 -t json -o ..\SocialMediaArchvingMeemoo\skraper\
```

Still only results in a json file with " only " data from 19 posts. How do I increase this?
On Windows and on Linux.

**Comment by sokomishalov** [comment]
Hi, thanks for raising this issue!
Well, it's not actually a number, it's a limit for posts.
` -n LIMIT, --limit LIMIT                   posts limit (50 by default)`
Most providers allow fetching only the latest posts, and currently, Facebook is one of them.
