### ISSUE TITLE
Gradle problem.

### ISSUE THREAD

**Issue by TheMajster** [SokoMishaLov/skraper#36]
Hello, i have problem with gradle.

![image](https://user-images.githubusercontent.com/16430891/82346740-241be080-99f7-11ea-8bd9-88c91ae9b191.png)

![image](https://user-images.githubusercontent.com/16430891/82346826-3d249180-99f7-11ea-8d6b-fd522a50a7a3.png)

**Comment by SokoMishaLov** [comment]
Hey, thanks for the issue!
Unfortunately, jitpack does not support maven "revision feature" which I added in 0.4.0.
I've reverted it and released 0.4.1, which solves this issue. Please upgrade it.
