### ISSUE TITLE
Can't import via gradle

### ISSUE THREAD

**Issue by ZueFe** [SokoMishaLov/skraper#38]
Hey, have issue with importing the library to my android app.

When using 
`implementation("com.github.sokomishalov.skraper:skrapers:0.4.0")`

I get following error: 
![obrazek](https://user-images.githubusercontent.com/2867084/82425455-d3ec5f00-9a86-11ea-8c10-7adb8a2b3294.png)

Checked jitpack.io which says I should use `implementation 'com.github.SokoMishaLov:skraper:0.4.0'` but when I do that, it can't find any package.
Thanks for the help!

**Comment by SokoMishaLov** [comment]
Hey, thanks for the issue!
Unfortunately, jitpack does not support maven "revision feature" which I added in 0.4.0.
I've reverted it and released 0.4.1, which solves this issue. Please upgrade it.
