### ISSUE TITLE
Twitter scraper

### ISSUE THREAD

**Issue by aditi1421** [sokomishalov/skraper#400]
Is this working for twitter since it recently removed all third party applications to use it's api and none of the libraries in python work now for scraping twitter data, do let me know your pov on this!

**Comment by hacknapier** [comment]
https://rapidapi.com/scraptubes/api/scraptubes

**Comment by sokomishalov** [comment]
Twitter scraper does not rely on a public API except for one small piece - it's used one time to retrieve video details in case of trying to download it via this tool. Actually, I haven't checked yet if that request is still available, but will do it soon
