### ISSUE TITLE
Can't resolve import ru.sokomishalov.skraper.model.AttachmentType.IMAGE

### ISSUE THREAD

**Issue by ZueFe** [SokoMishaLov/skraper#41]
Hello, trying to run the example, however, I can't seen to be able to find AttachmentType (neither IMAGE, nor VIDEO).

Has this changed? Thanks for the help

**Comment by SokoMishaLov** [comment]
Hey!
Thx for let me know. I've completely forgotten about example and missed some breaking changes in the library :)
Master branch is ok now
