### ISSUE TITLE
Facebook video can't be displayed in VideoView

### ISSUE THREAD

**Issue by ZueFe** [SokoMishaLov/skraper#44]
Thumbnail is null and url refers to a fb page with the video rather then the video itself. Not sure this can be fixed tho (or am I missing something?).

**Comment by SokoMishaLov** [comment]
Please provide more information about the URL.
I'm not sure, but VideoVIew might require an embedded FB video link and direct video file link instead of just normal.
For that kind of purposes, I've implemented `Skraper::resolve` method which allows you to try to get a direct media link.

**Comment by ZueFe** [comment]
@SokoMishaLov tried basically the same thing as in the example app you provided, setting url from media.url didn't work. I've tried to use resolve method too, using media[0] as parameter but that didn't seem to do the trick either.

URL certainly isn't direct video file link.
media.url looks something like this:
```
https://facebook.com/dracibrno/posts/2909186149189222?__xts__%5B0%5D=68.ARAZIdo26of6hfjYkdSDXkzo5AileX8nX6CKqdR8vmVFD-EVU9SQNfo4NgLGZZ6LlLmWNO2XQ1fVkVEeC-NTpViwNh12xtdTIdllq6zGdFQl_iDXJpHkY38DaDz5_ORC6UkWviilRJ8NXyC-m48tof-5R_Q4Z49GtSiZk8pP0xxbrgFcV1huEmQ_VakRgUvH5XgzNaVtFFKxa5zNsbGQ-Md4rspHSlbyqto_Wk4i5JWUmAD6c2jrgEjrkKvB3MnWoQcabYkvMpDUgTzf0X3iNo3mlthtm9enQKdxV0EskpJoziEEFfbVo7zbSwvxlcsNzAH7nJ1s40MCmp6BDRslNoln1A&__tn__=-R
```

resolved url:

```
https://facebook.com/dracibrno/posts/2909186149189222?__xts__%5B0%5D=68.ARDd1z4FcSY8WYKw6mqQw0tWoCtImpLUkmnQjQyHFYVN3YZtP6j2YMkTuPVff0U2bD09r0Bw1kfXfhfj7REybz2hifbZiCfcQ8aImJMB_lJwLiBPmh4V1hmLygLG1J24qLQwVu3BgWvg2YxEwVvU7tBC_OIKuzDJodJsy40oKVRhVG-vVvSnmS4DVCJcBaPsNClKB4wzRlrs1qEkJHuzFrc3kZYMCCGqftzq32TL1D9MZqpztj8vYH_A8hR6PXA7sDb6_wUw910dus786s3LqrOFr42hfuOvBRkEPlB9al6IjP8hA7aPmCH6FryDlM-aShCOxuxTLJ8tvFuZQQEyKfBv1g&__tn__=-R, aspectRatio=1.7777777777778, thumbnail=Image(url=https://scontent-prg1-1.xx.fbcdn.net/v/t31.0-1/p200x200/17631988_1248516661922854_2806175819465310376_o.png?_nc_cat=101&_nc_sid=dbb9e7&_nc_ohc=qTeHxY3_akQAX8bKlH4&_nc_ht=scontent-prg1-1.xx&oh=1b4613595ae61bfbe939017ca9046a98&oe=5EF368F7
```

**Comment by SokoMishaLov** [comment]
Thank you for the issue!
I've released 0.4.2 version with improved FB media handling.

**Comment by ZueFe** [comment]
@SokoMishaLov 
hey, thanks! Thumbnail is working now, but I still wasn't able to load video (either straight from url, or using resolved url) :(
Was trying it via your example application, unfortunately no clue what could be wrong :(

**Comment by SokoMishaLov** [comment]
Not at all, glad to hear that :)
I'll close this issue.
