### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by cornatul** [sokomishalov/skraper#450]
How can I run this inside a docker container ? 
What are the requirements 
I can spend some time creating a docker image If anyoane can help me with the requirements to run this

**Comment by sokomishalov** [comment]
I don't see any problems with running this inside the docker container, all you need is an installed jdk 1.8+ on your machine/inside your docker container

**Comment by cornatul** [comment]
I've managed to make it run inside the container . I would have been nice if it had an http api . I think I had to recompile it to make it work for my needs
