### ISSUE TITLE
question about inegration

### ISSUE THREAD

**Issue by dnikola** [SokoMishaLov/skraper#46]
Hi,

thanks for such great work.
Reading about possibility's of this plugin i see that can do a lot!

Can you tell me what would be the best proper way to connect it with my app written in PHP.

Regards!

**Comment by SokoMishaLov** [comment]
Thanks, I appreciate that :)
Well, I suppose it would not be simple to do, but you are always able to try using JPHP because the tool is built on top of JVM.
Please share any results it's gonna work :)
