### ISSUE TITLE
TikTok Scraper not working  returning null data

### ISSUE THREAD

**Issue by malookshah4** [sokomishalov/skraper#467]
val client = OkHttpSkraperClient()
                val sktr = TikTokSkraper(client)
                Log.d("TAG", "getProfileFromTiktok: ${sktr.getPageInfo(path = "/@$userName")}")
                
I tried this above code but it returned null data I tried another type of data too but got the same issue.

**Comment by sokomishalov** [comment]
Hey!
Yeah, most of the existing tiktok scrapers stopped working at some point (https://github.com/yt-dlp/yt-dlp/issues/8620).
They haven't found a workaround yet for this problem, and me neither unfortunately

Let's keep this issue opened until we find a way to resolve it
