### ISSUE TITLE
Custom scrapers

### ISSUE THREAD

**Issue by ZueFe** [SokoMishaLov/skraper#55]
Hello, is it/would it be possible to write your own scrapers, or to extend existing scrapers?
Currently trying to inherit from FacebookSkraper but this doesn't seem possible right now.
Thank you!

**Comment by SokoMishaLov** [comment]
Hey, @ZueFe!
Well, you are always able to use kotlin delegation for this overriding for non-open classes. 
https://kotlinlang.org/docs/reference/delegation.html

But I think It's ok to open all implementations.

**Comment by SokoMishaLov** [comment]
Available in 0.5.1.
Thanks for the issue!

**Comment by ZueFe** [comment]
Thanks I will check it out :)
